baseURL = "http://happycodeguru.github.io/"
languageCode = "en-us"
title = "Happy Code Guru"
theme = "soho"


[params]
description = "Dev Aashram!!"
# gravatar = "soho@example.com"
images = ["images/me2.png"]
profilePicture = "images/guru_avatar.jpg"
copyright = "Author Name"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/asthanarht/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://asthanarht.github.com"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://asthanarht.twitter.com"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"


  [markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4